### ISSUE TITLE
Revealing Card Image

### ISSUE THREAD

**Issue by chepurko** [CodyReichert/materializer#7]
Hi, I'm not sure if the Revealing Card Image works correctly. I'm trying to do:

```bash
[card_reveal title="A Revealing Card" img="/wp-content/uploads/sites/2/2017/04/pic.jpg"]

[card_open]
stuff.
[/card_open]

[/card_reveal]
```

But all I get is the picture of houses, located [here](https://i1.wp.com/simplyrets.com/images/scrot1.png?w=740&ssl=1), which seems to be a default image or something.

[This is my page](https://blog.abaranovskaya.com/%D0%BE-%D0%BD%D0%B0%D1%81/). Any ideas on whether I'm missing something?

**Comment by CodyReichert** [comment]
Ah, I see. It does look like there is a hard-coded image for that component here: https://github.com/CodyReichert/materializer/blob/8f3257d9ea37d342cbb5b1a70ee12b024941388a/components/cards.php#L154

The fix for this is to simply use the `img` variable that's declared a few lines up (similar to the other components in the file):

```html
<img src="<?php echo $img; ?>">
```

Would you like to submit a PR for that change? Happy to merge it if you do. If not, I can try and get a patch in there soon.

Thanks for reporting!

**Comment by chepurko** [comment]
Looks like it works. PR #8 .

**Comment by CodyReichert** [comment]
Hey @chepurko - just merged this in, thank you again, and let me know if you hit anything else!
